version: "3"


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_web3
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    env_file:
      - db_keys.txt
    command: ["sh", "-c", "python3 manage.py runserver 0.0.0.0:8000"]

  db:
    image: postgres
    container_name: postgres_db
    env_file:
      - db_keys.txt

  adminer:
    image: adminer
    container_name: admin_db1
    ports:
      - "8080:8080"