# Generated by Django 2.2.2 on 2020-07-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название события')),
                ('date_start', models.DateTimeField(verbose_name='Начало события')),
                ('date_stop', models.DateTimeField(blank=True, verbose_name='Окончание события')),
                ('reminder', models.TimeField(verbose_name='напомнить за...')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'события',
                'db_table': 'my_event',
            },
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
