# Generated by Django 2.2.2 on 2020-07-18 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0002_auto_20200718_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reminder',
            field=models.CharField(choices=[('За час', datetime.timedelta(0, 3600)), ('За 2 часа', datetime.timedelta(0, 7200)), ('За 4 часа', datetime.timedelta(0, 14400)), ('За день', datetime.timedelta(1)), ('За неделю', datetime.timedelta(7))], max_length=150, verbose_name='напомнить за...'),
        ),
    ]
