# Generated by Django 2.2.2 on 2020-07-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0004_auto_20200718_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_stop',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание события'),
        ),
    ]
