# Generated by Django 2.2.2 on 2020-07-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0005_auto_20200718_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tmp_duration_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
